### ISSUE TITLE
Request Friday bar presence

### ISSUE THREAD

**Issue by nc-kac** [bogeholm/mikkelsen_mplrc#1]
Jeg har sidste dag på Popeye i næste uge, så vi holder min sidste fredags bar på Popeye 18/9. 
Vil du med?

**Comment by bogeholm** [comment]
Sikke et tab for Popeye! Jeg har desværre planer om fredagen, men er fri lørdag 19/9 til en eksempelvis en burger i KBH? :-)

Hils @nc-msl, @nc-pvpm og @nc-aln 👍

**Comment by nc-kac** [comment]
Marc og jeg kan desværre ikke på lørdag. Så vi må finde en anden dag.
Min sidste Popeye fredagsbar bliver ihvertfald rykket til engang i oktober nu hvor der er startet endnu en corona nedlukning.

**Comment by bogeholm** [comment]
Med det seneste communique via andre kanaler anses dette som løst.
